language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
install: composer install
script: composer phpunit
after_script:
  - composer phpcs
  - composer phploc
  - composer phpcpd
  - composer phpmd
